version: "3.7"

services:
  goldofir_web_new:
    image: goldofir:latest
    networks:
      - network_public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.goldofir-new.rule=Host(`goldofir.me`)"
        - "traefik.http.routers.goldofir-new.entrypoints=websecure"
        - "traefik.http.routers.goldofir-new.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.goldofir-new.loadbalancer.server.port=80"
        - "traefik.http.routers.goldofir-new.service=goldofir-new"
        - "traefik.http.services.goldofir-new.loadbalancer.passhostheader=true"
        - "traefik.http.middlewares.goldofir-compress.compress=true"
        - "traefik.http.routers.goldofir-new.middlewares=goldofir-compress"

networks:
  network_public:
    external: true
