version: "3.7"

services:
  goldofir-web:
    image: ghcr.io/${GITHUB_USERNAME}/goldofir:latest
    container_name: goldofir-web
    restart: unless-stopped
    networks:
      - network_public
    deploy:
      labels:
        - "traefik.enable=true"
        
        # Middleware de redirecionamento (HTTPS obrigatório)
        - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
        
        # Roteador para o domínio principal (goldofir.me)
        - "traefik.http.routers.goldofir.rule=Host(`goldofir.me`)"
        - "traefik.http.routers.goldofir.entrypoints=websecure"
        - "traefik.http.routers.goldofir.tls.certresolver=letsencryptresolver"
        
        # Roteador HTTP para capturar e redirecionar para HTTPS
        - "traefik.http.routers.goldofir-http.rule=Host(`goldofir.me`)"
        - "traefik.http.routers.goldofir-http.entrypoints=web"
        - "traefik.http.routers.goldofir-http.middlewares=redirect-https@docker"
        
        # Configuração do serviço
        - "traefik.http.services.goldofir.loadbalancer.server.port=80"

networks:
  network_public:
    external: true

volumes:
  goldofir_data:
    external: true
    name: goldofir_data 