version: "3.7"

services:
  goldofir_goldofir-web:
    image: ghcr.io/goldofir/goldofir:latest
    volumes:
      - goldofir_data:/var/www/html
    networks:
      - network_public

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-https.redirectscheme.permanent=true"
        - "traefik.http.routers.goldofir.rule=Host(`goldofir.me`)"
        - "traefik.http.routers.goldofir.entrypoints=websecure"
        - "traefik.http.routers.goldofir.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.goldofir-http.rule=Host(`goldofir.me`)"
        - "traefik.http.routers.goldofir-http.entrypoints=web"
        - "traefik.http.routers.goldofir-http.middlewares=redirect-https@docker"
        - "traefik.http.services.goldofir.loadbalancer.server.port=80"

networks:
  network_public:
    external: true

volumes:
  goldofir_data:
    name: goldofir_data 
